source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'pg'
gem 'json'
gem 'httparty'
gem 'ruby-protocol-buffers'
gem 'whenever', :require => false